"""Self-host the three brand fonts.

Why: `next/font/google` fetches from fonts.googleapis.com AT BUILD TIME. That works locally but fails in
the Docker build (the builder has no outbound network for it), with:

    An error occurred in `next/font`.
    TypeError: Cannot read properties of null (reading '1')

Self-hosting removes the build-time network dependency entirely: the woff2 files ship in `public/fonts`
and are declared in CSS, so the build is hermetic and the runtime loads fonts from our own origin (faster
and no third-party request on page load).

Run once:  python3 scripts/selfhost_fonts.py
"""
from __future__ import annotations

import re
import pathlib
import subprocess
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "public" / "fonts"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# latin only: the app is English, and pulling every subset would add ~1MB for nothing.
FAMILIES = {
    "Inter": "Inter:wght@400;500;600;700",
    "Newsreader": "Newsreader:ital,wght@0,400;0,500;0,600;1,400",
    "JetBrains Mono": "JetBrains+Mono:wght@400;500",
}


def fetch(url: str) -> bytes:
    r = subprocess.run(["curl", "-sL", "--max-time", "60", "-A", UA, url], capture_output=True)
    if r.returncode != 0 or not r.stdout:
        raise RuntimeError(f"fetch failed: {url}")
    return r.stdout


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    css_parts: list[str] = [
        "/* Self-hosted brand fonts. Generated by scripts/selfhost_fonts.py — do not edit by hand.\n"
        "   next/font/google is deliberately NOT used: it fetches at build time, which fails in the\n"
        "   Docker builder. These files are latin-subset woff2 from Google Fonts (OFL). */\n"
    ]
    total = 0
    for family, spec in FAMILIES.items():
        slug = family.lower().replace(" ", "-")
        css_url = f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
        css = fetch(css_url).decode()
        # keep only the `latin` block(s); the comment above each @font-face names the subset
        blocks = re.findall(r"(/\*[^*]*\*/\s*@font-face\s*\{[^}]*\})", css, re.S)
        kept = 0
        for block in blocks:
            if "/* latin */" not in block:
                continue
            m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
            if not m:
                continue
            url = m.group(1)
            name = url.rsplit("/", 1)[-1]
            dest = OUT / f"{slug}-{name}"
            if not dest.exists():
                dest.write_bytes(fetch(url))
                total += 1
            css_parts.append(block.replace(url, f"/fonts/{dest.name}"))
            kept += 1
        print(f"{family}: {kept} latin face(s)")
        if kept == 0:
            print(f"  WARNING: no latin subset found for {family}", file=sys.stderr)

    css_out = pathlib.Path(__file__).resolve().parent.parent / "app" / "fonts.css"
    css_out.write_text("\n\n".join(css_parts) + "\n")
    print(f"\nwrote {css_out} and {total} new font file(s) to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
