import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import { themeScript } from "@/components/theme-toggle";

/**
 * Fonts are SELF-HOSTED (see app/fonts.css, generated by scripts/selfhost_fonts.py) rather than loaded
 * with `next/font/google`. Reason: next/font fetches from fonts.googleapis.com at build time, which fails
 * in the Docker builder with `An error occurred in next/font` / `Cannot read properties of null`. Self-hosting
 * makes the build hermetic and removes a third-party request from page load.
 *
 * The CSS variables below are the contract every component relies on.
 */

export const metadata: Metadata = {
  title: "pre-mortem — flag a business decision before you make it",
  description:
    "Describe a decision you are considering. It searches what your company has actually done before, flags what went wrong, and cites each past decision by id. When there is no precedent it says so.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      style={
        {
          "--font-inter": "'Inter', ui-sans-serif, system-ui, sans-serif",
          "--font-newsreader": "'Newsreader', Georgia, serif",
          "--font-jetbrains": "'JetBrains Mono', ui-monospace, monospace",
        } as React.CSSProperties
      }
    >
      <head>
        {/* applied before first paint so the stored theme does not flash */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="font-sans bg-paper text-ink">{children}</body>
    </html>
  );
}
